platform :ios, '8.0'

pod 'MDCSwipeToChoose', '0.2.0'
pod 'AFNetworking'
# pod 'JBWebViewController'
#pod 'DZNWebViewController'
pod 'CrashlyticsFramework'
pod 'CocoaLumberjack', '2.0.0-rc'
pod 'CrashlyticsLumberjack', '2.0.0-rc2'
pod 'JGProgressHUD'
pod 'SVProgressHUD'
pod 'libextobjc'       # Useful macros and some craziness
pod 'KVOController', '~> 1.0.3'
pod 'Bolts', '~> 1.1.4'
pod 'INTULocationManager', '~> 3.0.1'
pod 'hpple', '~> 0.2'