platform :ios, '8.0'

pod 'MDCSwipeToChoose'
pod 'AFNetworking'
pod 'KVOController'
pod 'JBWebViewController'
#pod 'DZNWebViewController'
pod 'CrashlyticsFramework'
pod 'CocoaLumberjack', '2.0.0-rc'
pod 'CrashlyticsLumberjack', '2.0.0-rc2'
pod 'JGProgressHUD'